"""
Demo sample hospital bill data.
Represents a realistic bill for a cardiac patient admitted to a private hospital in Mumbai.
Includes a mix of FAIR, OVERCHARGED, and SUSPICIOUS items to showcase the app's full capability.
"""

DEMO_PATIENT = {
    "name": "Mr. Rajesh Kumar",
    "age": 52,
    "gender": "Male",
    "patient_id": "MUM-2026-04821",
    "hospital": "City Heart & General Hospital",
    "city": "Mumbai",
    "ward": "Private Room → ICU",
    "diagnosis": "Acute Myocardial Infarction (Heart Attack)",
    "admission_date": "15-Mar-2026",
    "discharge_date": "19-Mar-2026",
    "duration_days": 4,
    "attending_doctor": "Dr. Suresh Mehta (Senior Cardiologist)",
    "bill_date": "19-Mar-2026",
    "bill_number": "INV-2026-18745",
}

# Each item: name, category, quantity, unit, unit_rate, amount
# These are raw bill items as a patient would see them
DEMO_BILL_ITEMS = [
    # ── Room & ICU ─────────────────────────────────────────────────────────────
    {
        "name": "Private Room",
        "category": "Room Charges",
        "quantity": 2,
        "unit": "days",
        "unit_rate": 8500.0,
        "amount": 17000.0,
    },
    {
        "name": "ICU Charges",
        "category": "Room Charges",
        "quantity": 2,
        "unit": "days",
        "unit_rate": 22000.0,
        "amount": 44000.0,
    },
    # ── Doctor Fees ────────────────────────────────────────────────────────────
    {
        "name": "Cardiologist Consultation",
        "category": "Doctor Fees",
        "quantity": 6,
        "unit": "visits",
        "unit_rate": 2500.0,
        "amount": 15000.0,
    },
    # ── Procedures ────────────────────────────────────────────────────────────
    {
        "name": "Angioplasty",
        "category": "Procedures",
        "quantity": 1,
        "unit": "procedure",
        "unit_rate": 175000.0,
        "amount": 175000.0,
    },
    {
        "name": "Coronary Angiography",
        "category": "Diagnostics",
        "quantity": 1,
        "unit": "procedure",
        "unit_rate": 18000.0,
        "amount": 18000.0,
    },
    # ── OT & Anesthesia ────────────────────────────────────────────────────────
    {
        "name": "Major OT Charges",
        "category": "OT & Anesthesia",
        "quantity": 1,
        "unit": "procedure",
        "unit_rate": 32000.0,
        "amount": 32000.0,
    },
    {
        "name": "General Anesthesia",
        "category": "OT & Anesthesia",
        "quantity": 1,
        "unit": "procedure",
        "unit_rate": 18000.0,
        "amount": 18000.0,
    },
    # ── Diagnostic Tests ───────────────────────────────────────────────────────
    {
        "name": "ECG",
        "category": "Diagnostics",
        "quantity": 8,
        "unit": "tests",
        "unit_rate": 600.0,
        "amount": 4800.0,
    },
    {
        "name": "Echocardiogram",
        "category": "Diagnostics",
        "quantity": 1,
        "unit": "test",
        "unit_rate": 5500.0,
        "amount": 5500.0,
    },
    {
        "name": "Complete Blood Count",
        "category": "Diagnostics",
        "quantity": 2,
        "unit": "tests",
        "unit_rate": 800.0,
        "amount": 1600.0,
    },
    {
        "name": "Lipid Profile",
        "category": "Diagnostics",
        "quantity": 1,
        "unit": "test",
        "unit_rate": 1200.0,
        "amount": 1200.0,
    },
    {
        "name": "Serum Electrolytes",
        "category": "Diagnostics",
        "quantity": 3,
        "unit": "tests",
        "unit_rate": 600.0,
        "amount": 1800.0,
    },
    {
        "name": "Coagulation Profile",
        "category": "Diagnostics",
        "quantity": 2,
        "unit": "tests",
        "unit_rate": 900.0,
        "amount": 1800.0,
    },
    {
        "name": "Chest X-Ray",
        "category": "Diagnostics",
        "quantity": 2,
        "unit": "tests",
        "unit_rate": 700.0,
        "amount": 1400.0,
    },
    # ── Medicines ──────────────────────────────────────────────────────────────
    {
        "name": "Aspirin 75mg",
        "category": "Medicines",
        "quantity": 30,
        "unit": "tablets",
        "unit_rate": 55.0,
        "amount": 1650.0,
    },
    {
        "name": "Clopidogrel 75mg",
        "category": "Medicines",
        "quantity": 30,
        "unit": "tablets",
        "unit_rate": 60.0,
        "amount": 1800.0,
    },
    {
        "name": "Atorvastatin 40mg",
        "category": "Medicines",
        "quantity": 30,
        "unit": "tablets",
        "unit_rate": 55.0,
        "amount": 1650.0,
    },
    {
        "name": "Pantoprazole 40mg",
        "category": "Medicines",
        "quantity": 30,
        "unit": "tablets",
        "unit_rate": 80.0,
        "amount": 2400.0,
    },
    {
        "name": "Heparin Injection",
        "category": "Medicines",
        "quantity": 10,
        "unit": "vials",
        "unit_rate": 450.0,
        "amount": 4500.0,
    },
    {
        "name": "IV Fluids",
        "category": "Medicines",
        "quantity": 8,
        "unit": "bottles",
        "unit_rate": 350.0,
        "amount": 2800.0,
    },
    {
        "name": "Ceftriaxone 1g Injection",
        "category": "Medicines",
        "quantity": 6,
        "unit": "vials",
        "unit_rate": 500.0,
        "amount": 3000.0,
    },
    # ── Consumables ────────────────────────────────────────────────────────────
    {
        "name": "IV Set",
        "category": "Consumables",
        "quantity": 6,
        "unit": "pieces",
        "unit_rate": 250.0,
        "amount": 1500.0,
    },
    {
        "name": "Surgical Gloves",
        "category": "Consumables",
        "quantity": 20,
        "unit": "pairs",
        "unit_rate": 150.0,
        "amount": 3000.0,
    },
    {
        "name": "Disposable Syringe",
        "category": "Consumables",
        "quantity": 15,
        "unit": "pieces",
        "unit_rate": 80.0,
        "amount": 1200.0,
    },
    {
        "name": "Foley Catheter",
        "category": "Consumables",
        "quantity": 1,
        "unit": "piece",
        "unit_rate": 800.0,
        "amount": 800.0,
    },
    # ── Nursing & Allied ───────────────────────────────────────────────────────
    {
        "name": "Nursing Charges",
        "category": "Nursing Services",
        "quantity": 4,
        "unit": "days",
        "unit_rate": 2000.0,
        "amount": 8000.0,
    },
    {
        "name": "Physiotherapy",
        "category": "Nursing Services",
        "quantity": 2,
        "unit": "sessions",
        "unit_rate": 1500.0,
        "amount": 3000.0,
    },
    {
        "name": "Dietitian Consultation",
        "category": "Nursing Services",
        "quantity": 4,
        "unit": "sessions",
        "unit_rate": 800.0,
        "amount": 3200.0,
    },
    # ── Administrative ─────────────────────────────────────────────────────────
    {
        "name": "Admission/Registration Fee",
        "category": "Administrative",
        "quantity": 1,
        "unit": "flat",
        "unit_rate": 3500.0,
        "amount": 3500.0,
    },
    {
        "name": "Ambulance Charges",
        "category": "Administrative",
        "quantity": 1,
        "unit": "trip",
        "unit_rate": 5000.0,
        "amount": 5000.0,
    },
    # ── SUSPICIOUS: items that should not be billed separately ─────────────────
    {
        "name": "Oxygen Charges",
        "category": "Other",
        "quantity": 4,
        "unit": "days",
        "unit_rate": 1500.0,
        "amount": 6000.0,
    },
]
